name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  flatpak:
    name: "Flatpak"
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-44
      options: --privileged
    steps:
    - uses: actions/checkout@v4
    - uses: flatpak/flatpak-github-actions/flatpak-builder@v6
      with:
        bundle: palette.flatpak
        manifest-path: 64gram.yml
        cache-key: flatpak-builder-${{ github.sha }}

id: Telegram.TelegramDesktop.Store
runtime: org.freedesktop.Platform
runtime-version: "22.08"
sdk: org.freedesktop.Sdk
command: 64gram
finish-args:
  - --share=network
  - --socket=x11
  - --socket=wayland
  - --device=dri
  - --filesystem=host
modules:
  - name: qt5
    buildsystem: cmake
    sources:
      - type: git
        url: https://github.com/qt/qt5.git
        branch: "6.8"
  - name: 64gram
    buildsystem: cmake
    sources:
      - type: git
        url: https://github.com/TDesktop-x64/tdesktop.git
        branch: dev
