name: Flatpak Build

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and deploy Flatpak
        uses: flatpak/action@v1
        with:
          repository: myself-6264/flatpak-github-actions
          app-id: org.example.MyApp.Devel
          build-path: .
          commit-message: "Automated build"
          manifest-path: org.64gram.Telegram.yml
          branch: dev
          filename: my-telegram-app.flatpak

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: my-telegram-app
          path: my-telegram-app.flatpak
